config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'select' => 'main#select'
  get 'query' => 'main#query'
  get 'result' => 'main#result'
end

app/models/student.rb
class Student < ActiveRecord::Base

  # The columns of the dataset, a list of hashes with name, desc, and values.
  def self.ds_columns
    @@DSColumns
  end

  # Only the names (not descriptions) of the dataset columns
  def self.ds_column_names
    @@DSColumns.map do |c|
      c[:name]
    end
  end

  # Receives a name (value) and outputs its description
  def self.description_for name, value
    @@DSColumns.find do |c|
      c[:name] == name
    end[:values].find do |v|
      v[0] == value
    end[1]
  end

  @@EducationLevels = [['0', 'None'], ['1', 'Up to 4th grad'],
    ['2', '5th to 9th grade'], ['3', 'Secondary education'],
    ['4', 'Higher education']]

  @@Jobs = [['teacher', 'Teacher'], ['Health', 'Health care-related'],
    ['services', 'Civil services'], ['at_home', 'At home'], ['other', 'Other']]

  @@YesNo = [%w(yes Yes), %w(no No)]

  @@Qualities = %w(Terrible Bad Okay Good Excellent).each.with_index.map do |q, i|
    [(i + 1).to_s, q]
  end

  @@Amounts = %w(Lowest Low Medium High Hightest).each.with_index.map do |a, i|
    [(i + 1).to_s, a]
  end

  @@Grades = (0..20).map{|i| [i.to_s, i.to_s]}

  @@DSColumns = [
    {
      name: 'sex',
      desc: 'Sex',
      values: [%w(F Female), %w(M Male)]
    },
    {
      name: 'age',
      desc: 'Age',
      values: (15..22).map { |i| [i.to_s, i.to_s] }
    },
    {
      name: 'address',
      desc: 'Address',
      values: [%w(U Urban), %w(R Rural)]
    },
    {
      name: 'famsize',
      desc: 'Family size',
      values: [['LE3', '<= 3'], ['GT3', '> 3']]
    },
    {
      name: 'Pstatus',
      desc: 'Parent\'s cohabitation status',
      values: [%w(T Together), %w(A Apart)]
    },
    {
      name: 'Medu',
      desc: 'Mother\'s education level',
      values: @@EducationLevels
    },
    {
      name: 'Fedu',
      desc: 'Father\'s education level',
      values: @@EducationLevels
    },
    {
      name: 'Mjob',
      desc: 'Mother\'s ocupation',
      values: @@Jobs
    },
    {
      name: 'Fjob',
      desc: 'Father\'s ocupation',
      values: @@Jobs
    },
    {
      name: 'reason',
      desc: 'Reason for choosing this school',
      values: [['home', 'Close to home'],
        ['reputation', 'School\'s reputation'], ['course', 'Course preference'],
        ['other', 'Other']]
    },
    {
      name: 'guardian',
      desc: 'Guardian',
      values: [%w(mother Mother), %w(father Father), %w(other Other)]
    },
    {
      name: 'traveltime',
      desc: 'Travel time',
      values: [['1', '< 15 min'], ['2', '15-30 min'], ['3', '30 min - 1 hour'],
        ['4', '> 1 hour']]
    },
    {
      name: 'studytime',
      desc: 'Weekly study time',
      values: [['1', '< 2 hour'], ['2', '2-5 hour'], ['3', '5-10 hour'],
        ['4', '> 10 hour']]
    },
    {
      name: 'failures',
      desc: 'Number of past class failures',
      values: (1..3).map{|i| [i.to_s, i.to_s]} + [['4', '> 3']]
    },
    {
      name: 'schoolsup',
      desc: 'Extra educational support',
      values: @@YesNo
    },
    {
      name: 'famsup',
      desc: 'Family education support',
      values: @@YesNo
    },
    {
      name: 'paid',
      desc: 'Extra paid classes within the course subject',
      values: @@YesNo
    },
    {
      name: 'activities',
      desc: 'Extra curricular activities',
      values: @@YesNo
    },
    {
      name: 'nursery',
      desc: 'Attended nursery school',
      values: @@YesNo
    },
    {
      name: 'higher',
      desc: 'Intention to take higher education',
      values: @@YesNo
    },
    {
      name: 'internet',
      desc: 'Internet access from home',
      values: @@YesNo
    },
    {
      name: 'romantic',
      desc: 'With a romantic relationship',
      values: @@YesNo
    },
    {
      name: 'famrel',
      desc: 'Quality of family relationships',
      values: @@Qualities
    },
    {
      name: 'freetime',
      desc: 'Free time after school',
      values: @@Amounts
    },
    {
      name: 'goout',
      desc: 'Going out with friends',
      values: @@Amounts
    },
    {
      name: 'Dalc',
      desc: 'Workday alcohol consumption',
      values: @@Amounts
    },
    {
      name: 'Walc',
      desc: 'Weekend alcohol consumption',
      values: @@Amounts
    },
    {
      name: 'health',
      desc: 'Current health status',
      values: @@Qualities
    },
    {
      name: 'absences',
      desc: 'Number of school absences',
      values: (0..93).map{|i| [i.to_s, i.to_s]}
    },
    {
      name: 'G1',
      desc: 'First midterm grade',
      values: @@Grades
    },
    {
      name: 'G2',
      desc: 'Second midterm grade',
      values: @@Grades
    },
    {
      name: 'G3',
      desc: 'Third midterm grade',
      values: @@Grades
    }
  ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  @@Option = Struct.new :name, :desc

  def index
  end

  def select
    @options = Student::ds_columns.map{|c| @@Option::new c[:name], c[:desc]}
  end

  def query
    class_name = params[:column]
    @class_column = Student::ds_columns.find{|c| c[:name] == class_name }[:desc]
    @columns = Student::ds_columns.select do |c|
      c[:name] != class_name
    end.map do |c|
      {
        name: c[:name],
        desc: c[:desc],
        values: c[:values].map{|v| @@Option::new v[0], v[1]}
      }
    end
  end

  def result
    @class_col = Student::ds_columns.find do |c|
      not params.keys.include? c[:name]
    end
    @query_parameters = params.select do |k, v|
      k.in? Student::ds_column_names
    end
    dataset = Baobab::Dataset::new student_list
    @tree = Baobab::DecisionTree::new dataset, @class_col[:name]
    result = @tree.query @query_parameters
    @result = Student::description_for @class_col[:name], result
  end

private

  # Returns a list of hashes that can be fed into a dataset
  def student_list
    Student::all.map do |s|
      s.attributes.except 'id', 'created_at', 'updated_at'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Performance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<main>
  <h1>
    <a href="/">
      Student Performance
    </a>
  </h1>

  <%= yield %>
</main>

</body>
</html>

app/views/main/index.html.erb
<h2>
  About
</h2>

<p>
	This is a web application that predicts student's performance in math and Portuguese class using an <a href="http://en.wikipedia.org/wiki/ID3_algorithm">ID3 algorithm</a> implemented in <a href="https://github.com/jleeothon/baobab">baobab</a>.
</p>

<p>
	The dataset is attributed to:
</p>

<p>
	P. Cortez and A. Silva. Using Data Mining to Predict Secondary School Student Performance. In A. Brito and J. Teixeira Eds., Proceedings of 5th FUture BUsiness TEChnology Conference (FUBUTEC 2008) pp. 5-12, Porto, Portugal, April, 2008, EUROSIS, ISBN 978-9077381-39-7. <a href="http://www3.dsi.uminho.pt/pcortez/student.pdf">Link</a>.
</p>


<p>
	And was taken in April 2015 from <a href="http://archive.ics.uci.edu/ml/datasets/Student+Performance">here</a>.
</p>

<h2>
	Get started!
</h2>

<%= link_to 'Predict your grades', {action: :select}, class: 'btn btn-primary' %>

app/views/main/query.html.erb
<%= form_tag 'result', method: 'get' do %>
  <% @columns.each do |column| %>
    <div class="form-group">
      <%= label_tag column[:name], column[:desc] %>
      <%= select_tag column[:name], options_from_collection_for_select(column[:values], :name, :desc) %>
    </div>
  <% end %>
  <div class="form-group">
    <%= submit_tag "Predict my #{@class_column.downcase}", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/main/result.html.erb
<p>
  Your <%= @class_col[:desc].downcase %> is likely to be: <%= @result %>
</p>

app/views/main/select.html.erb
<%= form_tag query_path, method: 'get' do %>
  <div>
    <%= label_tag 'column', 'What do you want to diagnose or predict?' %>
    <%= select_tag 'column', options_from_collection_for_select(@options, :name, :desc)  %>
  </div>
  <div>
    <%= submit_tag 'Go!', class: 'btn btn-primary' %>
  </div>
<% end %>